import PyInstaller.__main__

PyInstaller.__main__.run([ 
    '--hidden-import',
    'serial',
    'cli.py',
    '--clean',
    '-n',
    'Vbite_Flasher',
    # '--noconsole',
    '--windowed',
    # '--onedir',
    '--noconfirm',
    '--icon',
    'favicon.ico',

    # '--log-level',
    # 'DEBUG',
    # '-d',
    # 'imports',
    # '--add-data',
    # 'C:/Users/adilo/.pyenv/pyenv-win/versions/3.11.0b4/Lib/site-packages/customtkinter;customtkinter/',
   # '../../../../Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/customtkinter:customtkinter/',
    '--add-data',
    'Flasher/GUI/images/favicon.ico;Flasher/GUI/images/',
    # '--add-data',
    # 'Flasher/custom_color.json;Flasher/',
    '--add-data',
    'Flasher/GUI/mainUI.qml;Flasher/GUI/',
    '--add-data',
    'esp_idf_win/.;esp_idf_win/.',
    '--add-data',
    'Flasher/configuration/*.csv;Flasher/configuration/',
    '--add-data',
    'Flasher/configuration/*.bin;Flasher/configuration/'
])